# Cấu hình Database
# Ưu tiên lấy giá trị từ biến môi trường (Docker), nếu không sẽ dùng mặc định (Local Laragon)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/trantuankiet?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect # Hibernate sẽ tự động nhận diện

# Thymeleaf
spring.thymeleaf.cache=false
